---
# tasks file for ansible-role-configure-php-ini

- name: Configure cli/php.ini file
  lineinfile:
    path: "{{ cli_php_ini_path }}"
    regexp: "{{ item.parameter }} ="
    line: "{{ item.parameter }} = {{ item.value }}"
    backup: yes
  with_items: "{{ cli_php_ini_parameters_and_values }}"
  notify:
    - reload apache2


- name: Configure apache2/php.ini file
  lineinfile:
    path: "{{ apache_php_ini_path }}"
    regexp: "{{ item.parameter }} ="
    line: "{{ item.parameter }} = {{ item.value }}"
    backup: yes
  with_items: "{{ apache_php_ini_parameters_and_values }}"
  notify:
    - reload apache2